const CONNECT = 'CONNECT';
const CREATE = 'CREATE';
const CREATED = 'CREATED';
const JOIN = 'JOIN';
const JOINED = 'JOINED';
const FOODCOLLISION = 'FOODCOLLISION';
const PLAY = 'PLAY';
const FOODATE = 'FOODATE';
const DIRECTIONCHANGE = 'DIRECTIONCHANGE';
const DIRECTIONCHANGED = 'DIRECTIONCHANGED';
const UPDATE = 'UPDATE';

module.exports = { CONNECT, CREATE, CREATED, JOIN, JOINED, UPDATE, PLAY, FOODATE, DIRECTIONCHANGE, DIRECTIONCHANGED, FOODCOLLISION }